### ISSUE TITLE
Parsing of json never ends.

### ISSUE THREAD

**Issue by XavDCtpz** [SMH17/TensorBoxPy3#1]
Hi !
I am kind of new to deep learning and have an object detection problem to solve.
I've run the training script on the brainwash dataset and everything went fine. But now I'm trying to run it on my own data, and can't make it work.
My dataset contains 81 by 81 pixels jpeg images, and I have used the make_json.py script to generate the training bounding boxes. I have meticulously checked the json file, and it does have exactly the right structure.
But when I launch the command `python3 train.py --hypes hypes/inception_rezoom.json --max_iter=2000 --logdir output  `  the script seems to freeze after printing `Parsing: my_file.json`

I can't work out what the problem is here. Do the training images have to be of a specific size or format ? or is it anything else ?

Thanks in advance for your help,

Regards,
Xavier.

**Comment by SMH17** [comment]
Check the hype files. The default configuration is set to use 640x480 images, if you want to use datasets with images of different size you have to adjust parameters as well.

**Comment by XavDCtpz** [comment]
Thanks for your fast answer ! I fixed it now, but then I got a whole new bunch of errors. So can I ask for your help again maybe ?
It seems that Tensorflow is not able to reshape some tensor or something like that. Here's the full stacktrace :

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/common_shapes.py", line 671, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot reshape a tensor with 7488 elements to shape [300,832] (249600 elements) for 'Reshape' (op: 'Reshape') with input shapes: [1,3,3,832], [2] and with input tensors computed as partial shapes: input[1] = [300,832].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 592, in <module>
    main()
  File "train.py", line 589, in main
    train(H, test_images=[])
  File "train.py", line 490, in train
    smooth_op, global_step, learning_rate) = build(H, q)
  File "train.py", line 385, in build
    boxes_loss[phase]) = build_forward_backward(H, x, phase, boxes, flags)
  File "train.py", line 286, in build_forward_backward
    pred_confidences, pred_confs_deltas, pred_boxes_deltas) = build_forward(H, x, phase, reuse)
  File "train.py", line 167, in build_forward
    [H['batch_size'] * H['grid_width'] * H['grid_height'], H['later_feat_channels']])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 2510, in reshape
    name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2338, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1719, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1669, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Cannot reshape a tensor with 7488 elements to shape [300,832] (249600 elements) for 'Reshape' (op: 'Reshape') with input shapes: [1,3,3,832], [2] and with input tensors computed as partial shapes: input[1] = [300,832].
```

Thanks again in advance !
